# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'controler.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(700, 500)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.btStart = QtGui.QPushButton(self.centralwidget)
        self.btStart.setGeometry(QtCore.QRect(575, 420, 100, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btStart.setFont(font)
        self.btStart.setStyleSheet(_fromUtf8("background-color: rgb(0, 85, 0);"))
        self.btStart.setObjectName(_fromUtf8("btStart"))
        self.btnStop = QtGui.QPushButton(self.centralwidget)
        self.btnStop.setEnabled(False)
        self.btnStop.setGeometry(QtCore.QRect(460, 420, 100, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btnStop.setFont(font)
        self.btnStop.setStyleSheet(_fromUtf8("background-color: rgb(85, 0, 0);"))
        self.btnStop.setObjectName(_fromUtf8("btnStop"))
        self.btnEnd = QtGui.QPushButton(self.centralwidget)
        self.btnEnd.setGeometry(QtCore.QRect(20, 420, 130, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btnEnd.setFont(font)
        self.btnEnd.setStyleSheet(_fromUtf8("background-color: rgb(37, 0, 111);"))
        self.btnEnd.setObjectName(_fromUtf8("btnEnd"))
        self.gbStation1 = QtGui.QGroupBox(self.centralwidget)
        self.gbStation1.setGeometry(QtCore.QRect(300, 10, 151, 120))
        self.gbStation1.setStyleSheet(_fromUtf8("QGroupBox {\n"
"    border: 1px solid white;\n"
"    border-radius: 9px;\n"
"    margin-top: 0.5em;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    left: 10px;\n"
"    padding: 0 3px 0 3px;\n"
"}"))
        self.gbStation1.setCheckable(True)
        self.gbStation1.setObjectName(_fromUtf8("gbStation1"))
        self.lblSt1Smpl1 = QtGui.QLabel(self.gbStation1)
        self.lblSt1Smpl1.setGeometry(QtCore.QRect(10, 20, 100, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lblSt1Smpl1.setFont(font)
        self.lblSt1Smpl1.setObjectName(_fromUtf8("lblSt1Smpl1"))
        self.lblSt1Smpl1State = QtGui.QLabel(self.gbStation1)
        self.lblSt1Smpl1State.setGeometry(QtCore.QRect(110, 20, 20, 20))
        self.lblSt1Smpl1State.setStyleSheet(_fromUtf8("border: 1px;\n"
"border-radius: 10px;\n"
"background-color: rgb(255, 0, 0);"))
        self.lblSt1Smpl1State.setText(_fromUtf8(""))
        self.lblSt1Smpl1State.setObjectName(_fromUtf8("lblSt1Smpl1State"))
        self.lblSt1Smpl2 = QtGui.QLabel(self.gbStation1)
        self.lblSt1Smpl2.setGeometry(QtCore.QRect(10, 55, 100, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lblSt1Smpl2.setFont(font)
        self.lblSt1Smpl2.setObjectName(_fromUtf8("lblSt1Smpl2"))
        self.lblSt1Smpl2State = QtGui.QLabel(self.gbStation1)
        self.lblSt1Smpl2State.setGeometry(QtCore.QRect(110, 55, 20, 20))
        self.lblSt1Smpl2State.setStyleSheet(_fromUtf8("border: 1px;\n"
"border-radius: 10px;\n"
"background-color: rgb(255, 0, 0);"))
        self.lblSt1Smpl2State.setText(_fromUtf8(""))
        self.lblSt1Smpl2State.setObjectName(_fromUtf8("lblSt1Smpl2State"))
        self.lblSt1Smpl3 = QtGui.QLabel(self.gbStation1)
        self.lblSt1Smpl3.setGeometry(QtCore.QRect(10, 90, 100, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lblSt1Smpl3.setFont(font)
        self.lblSt1Smpl3.setObjectName(_fromUtf8("lblSt1Smpl3"))
        self.lblSt1Smpl3State = QtGui.QLabel(self.gbStation1)
        self.lblSt1Smpl3State.setGeometry(QtCore.QRect(110, 90, 20, 20))
        self.lblSt1Smpl3State.setStyleSheet(_fromUtf8("border: 1px;\n"
"border-radius: 10px;\n"
"background-color: rgb(255, 0, 0);"))
        self.lblSt1Smpl3State.setText(_fromUtf8(""))
        self.lblSt1Smpl3State.setObjectName(_fromUtf8("lblSt1Smpl3State"))
        self.logView = QtGui.QTextEdit(self.centralwidget)
        self.logView.setGeometry(QtCore.QRect(10, 10, 270, 321))
        self.logView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.logView.setReadOnly(True)
        self.logView.setObjectName(_fromUtf8("logView"))
        self.gbStation2 = QtGui.QGroupBox(self.centralwidget)
        self.gbStation2.setGeometry(QtCore.QRect(300, 140, 151, 120))
        self.gbStation2.setStyleSheet(_fromUtf8("QGroupBox {\n"
"    border: 1px solid white;\n"
"    border-radius: 9px;\n"
"    margin-top: 0.5em;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    left: 10px;\n"
"    padding: 0 3px 0 3px;\n"
"}"))
        self.gbStation2.setCheckable(True)
        self.gbStation2.setObjectName(_fromUtf8("gbStation2"))
        self.lblSt2Smpl1 = QtGui.QLabel(self.gbStation2)
        self.lblSt2Smpl1.setGeometry(QtCore.QRect(10, 20, 100, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lblSt2Smpl1.setFont(font)
        self.lblSt2Smpl1.setObjectName(_fromUtf8("lblSt2Smpl1"))
        self.lblSt2Smpl1State = QtGui.QLabel(self.gbStation2)
        self.lblSt2Smpl1State.setGeometry(QtCore.QRect(110, 20, 20, 20))
        self.lblSt2Smpl1State.setStyleSheet(_fromUtf8("border: 1px;\n"
"border-radius: 10px;\n"
"background-color: rgb(255, 0, 0);"))
        self.lblSt2Smpl1State.setText(_fromUtf8(""))
        self.lblSt2Smpl1State.setObjectName(_fromUtf8("lblSt2Smpl1State"))
        self.lblSt2Smpl2 = QtGui.QLabel(self.gbStation2)
        self.lblSt2Smpl2.setGeometry(QtCore.QRect(10, 55, 100, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lblSt2Smpl2.setFont(font)
        self.lblSt2Smpl2.setObjectName(_fromUtf8("lblSt2Smpl2"))
        self.lblSt2Smpl2State = QtGui.QLabel(self.gbStation2)
        self.lblSt2Smpl2State.setGeometry(QtCore.QRect(110, 55, 20, 20))
        self.lblSt2Smpl2State.setStyleSheet(_fromUtf8("border: 1px;\n"
"border-radius: 10px;\n"
"background-color: rgb(255, 0, 0);"))
        self.lblSt2Smpl2State.setText(_fromUtf8(""))
        self.lblSt2Smpl2State.setObjectName(_fromUtf8("lblSt2Smpl2State"))
        self.lblSt2Smpl3 = QtGui.QLabel(self.gbStation2)
        self.lblSt2Smpl3.setGeometry(QtCore.QRect(10, 90, 100, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lblSt2Smpl3.setFont(font)
        self.lblSt2Smpl3.setObjectName(_fromUtf8("lblSt2Smpl3"))
        self.lblSt2Smpl3State = QtGui.QLabel(self.gbStation2)
        self.lblSt2Smpl3State.setGeometry(QtCore.QRect(110, 90, 20, 20))
        self.lblSt2Smpl3State.setStyleSheet(_fromUtf8("border: 1px;\n"
"border-radius: 10px;\n"
"background-color: rgb(255, 0, 0);"))
        self.lblSt2Smpl3State.setText(_fromUtf8(""))
        self.lblSt2Smpl3State.setObjectName(_fromUtf8("lblSt2Smpl3State"))
        self.gbStation3 = QtGui.QGroupBox(self.centralwidget)
        self.gbStation3.setGeometry(QtCore.QRect(300, 270, 151, 120))
        self.gbStation3.setStyleSheet(_fromUtf8("QGroupBox {\n"
"    border: 1px solid white;\n"
"    border-radius: 9px;\n"
"    margin-top: 0.5em;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    left: 10px;\n"
"    padding: 0 3px 0 3px;\n"
"}"))
        self.gbStation3.setCheckable(True)
        self.gbStation3.setObjectName(_fromUtf8("gbStation3"))
        self.lblSt3Smpl1 = QtGui.QLabel(self.gbStation3)
        self.lblSt3Smpl1.setGeometry(QtCore.QRect(10, 20, 100, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lblSt3Smpl1.setFont(font)
        self.lblSt3Smpl1.setObjectName(_fromUtf8("lblSt3Smpl1"))
        self.lblSt3Smpl1State = QtGui.QLabel(self.gbStation3)
        self.lblSt3Smpl1State.setGeometry(QtCore.QRect(110, 20, 20, 20))
        self.lblSt3Smpl1State.setStyleSheet(_fromUtf8("border: 1px;\n"
"border-radius: 10px;\n"
"background-color: rgb(255, 0, 0);"))
        self.lblSt3Smpl1State.setText(_fromUtf8(""))
        self.lblSt3Smpl1State.setObjectName(_fromUtf8("lblSt3Smpl1State"))
        self.lblSt3Smpl2 = QtGui.QLabel(self.gbStation3)
        self.lblSt3Smpl2.setGeometry(QtCore.QRect(10, 55, 100, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lblSt3Smpl2.setFont(font)
        self.lblSt3Smpl2.setObjectName(_fromUtf8("lblSt3Smpl2"))
        self.lblSt3Smpl2State = QtGui.QLabel(self.gbStation3)
        self.lblSt3Smpl2State.setGeometry(QtCore.QRect(110, 55, 20, 20))
        self.lblSt3Smpl2State.setStyleSheet(_fromUtf8("border: 1px;\n"
"border-radius: 10px;\n"
"background-color: rgb(255, 0, 0);"))
        self.lblSt3Smpl2State.setText(_fromUtf8(""))
        self.lblSt3Smpl2State.setObjectName(_fromUtf8("lblSt3Smpl2State"))
        self.lblSt3Smpl3 = QtGui.QLabel(self.gbStation3)
        self.lblSt3Smpl3.setGeometry(QtCore.QRect(10, 90, 100, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lblSt3Smpl3.setFont(font)
        self.lblSt3Smpl3.setObjectName(_fromUtf8("lblSt3Smpl3"))
        self.lblSt3Smpl3State = QtGui.QLabel(self.gbStation3)
        self.lblSt3Smpl3State.setGeometry(QtCore.QRect(110, 90, 20, 20))
        self.lblSt3Smpl3State.setStyleSheet(_fromUtf8("border: 1px;\n"
"border-radius: 10px;\n"
"background-color: rgb(255, 0, 0);"))
        self.lblSt3Smpl3State.setText(_fromUtf8(""))
        self.lblSt3Smpl3State.setObjectName(_fromUtf8("lblSt3Smpl3State"))
        self.tBtnFileSelect = QtGui.QPushButton(self.centralwidget)
        self.tBtnFileSelect.setGeometry(QtCore.QRect(250, 360, 29, 29))
        self.tBtnFileSelect.setObjectName(_fromUtf8("tBtnFileSelect"))
        self.lblReportFileName = QtGui.QLabel(self.centralwidget)
        self.lblReportFileName.setGeometry(QtCore.QRect(10, 340, 91, 20))
        self.lblReportFileName.setObjectName(_fromUtf8("lblReportFileName"))
        self.lEditFileName = QtGui.QLineEdit(self.centralwidget)
        self.lEditFileName.setGeometry(QtCore.QRect(10, 360, 231, 29))
        self.lEditFileName.setObjectName(_fromUtf8("lEditFileName"))
        self.gbParams = QtGui.QGroupBox(self.centralwidget)
        self.gbParams.setGeometry(QtCore.QRect(460, 10, 231, 171))
        self.gbParams.setStyleSheet(_fromUtf8("QGroupBox {\n"
"    border: 1px solid white;\n"
"    border-radius: 9px;\n"
"    margin-top: 0.5em;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    left: 10px;\n"
"    padding: 0 3px 0 3px;\n"
"}"))
        self.gbParams.setCheckable(False)
        self.gbParams.setObjectName(_fromUtf8("gbParams"))
        self.sBoxCycleCounter = QtGui.QSpinBox(self.gbParams)
        self.sBoxCycleCounter.setGeometry(QtCore.QRect(135, 133, 80, 22))
        self.sBoxCycleCounter.setAlignment(QtCore.Qt.AlignCenter)
        self.sBoxCycleCounter.setMaximum(9999)
        self.sBoxCycleCounter.setProperty("value", 10)
        self.sBoxCycleCounter.setObjectName(_fromUtf8("sBoxCycleCounter"))
        self.sBoxInAirTime = QtGui.QSpinBox(self.gbParams)
        self.sBoxInAirTime.setGeometry(QtCore.QRect(135, 106, 80, 22))
        self.sBoxInAirTime.setAlignment(QtCore.Qt.AlignCenter)
        self.sBoxInAirTime.setButtonSymbols(QtGui.QAbstractSpinBox.PlusMinus)
        self.sBoxInAirTime.setSpecialValueText(_fromUtf8(""))
        self.sBoxInAirTime.setMaximum(9999)
        self.sBoxInAirTime.setProperty("value", 10)
        self.sBoxInAirTime.setObjectName(_fromUtf8("sBoxInAirTime"))
        self.sBoxFillTime = QtGui.QSpinBox(self.gbParams)
        self.sBoxFillTime.setGeometry(QtCore.QRect(135, 22, 80, 22))
        self.sBoxFillTime.setAlignment(QtCore.Qt.AlignCenter)
        self.sBoxFillTime.setButtonSymbols(QtGui.QAbstractSpinBox.PlusMinus)
        self.sBoxFillTime.setMaximum(9999)
        self.sBoxFillTime.setProperty("value", 60)
        self.sBoxFillTime.setObjectName(_fromUtf8("sBoxFillTime"))
        self.sBoxDischargeTime = QtGui.QSpinBox(self.gbParams)
        self.sBoxDischargeTime.setGeometry(QtCore.QRect(135, 79, 80, 22))
        self.sBoxDischargeTime.setAlignment(QtCore.Qt.AlignCenter)
        self.sBoxDischargeTime.setButtonSymbols(QtGui.QAbstractSpinBox.PlusMinus)
        self.sBoxDischargeTime.setSpecialValueText(_fromUtf8(""))
        self.sBoxDischargeTime.setMaximum(9999)
        self.sBoxDischargeTime.setProperty("value", 60)
        self.sBoxDischargeTime.setObjectName(_fromUtf8("sBoxDischargeTime"))
        self.sBoxInFluidTime = QtGui.QSpinBox(self.gbParams)
        self.sBoxInFluidTime.setGeometry(QtCore.QRect(135, 51, 80, 22))
        self.sBoxInFluidTime.setAlignment(QtCore.Qt.AlignCenter)
        self.sBoxInFluidTime.setButtonSymbols(QtGui.QAbstractSpinBox.PlusMinus)
        self.sBoxInFluidTime.setSpecialValueText(_fromUtf8(""))
        self.sBoxInFluidTime.setMaximum(9999)
        self.sBoxInFluidTime.setProperty("value", 10)
        self.sBoxInFluidTime.setObjectName(_fromUtf8("sBoxInFluidTime"))
        self.pBtnFill = QtGui.QPushButton(self.gbParams)
        self.pBtnFill.setGeometry(QtCore.QRect(10, 22, 120, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pBtnFill.setFont(font)
        self.pBtnFill.setFlat(True)
        self.pBtnFill.setObjectName(_fromUtf8("pBtnFill"))
        self.pBtnInFluid = QtGui.QPushButton(self.gbParams)
        self.pBtnInFluid.setGeometry(QtCore.QRect(10, 51, 120, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pBtnInFluid.setFont(font)
        self.pBtnInFluid.setFlat(True)
        self.pBtnInFluid.setObjectName(_fromUtf8("pBtnInFluid"))
        self.pBtnDischarge = QtGui.QPushButton(self.gbParams)
        self.pBtnDischarge.setGeometry(QtCore.QRect(10, 79, 120, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pBtnDischarge.setFont(font)
        self.pBtnDischarge.setFlat(True)
        self.pBtnDischarge.setObjectName(_fromUtf8("pBtnDischarge"))
        self.pBtnInAir = QtGui.QPushButton(self.gbParams)
        self.pBtnInAir.setGeometry(QtCore.QRect(10, 106, 120, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pBtnInAir.setFont(font)
        self.pBtnInAir.setFlat(True)
        self.pBtnInAir.setObjectName(_fromUtf8("pBtnInAir"))
        self.pBtnCycleCounter = QtGui.QPushButton(self.gbParams)
        self.pBtnCycleCounter.setGeometry(QtCore.QRect(10, 133, 120, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pBtnCycleCounter.setFont(font)
        self.pBtnCycleCounter.setFlat(True)
        self.pBtnCycleCounter.setObjectName(_fromUtf8("pBtnCycleCounter"))
        self.pBarStateProgress = QtGui.QProgressBar(self.centralwidget)
        self.pBarStateProgress.setGeometry(QtCore.QRect(470, 270, 211, 23))
        self.pBarStateProgress.setProperty("value", 0)
        self.pBarStateProgress.setObjectName(_fromUtf8("pBarStateProgress"))
        self.lblActualCycle = QtGui.QLabel(self.centralwidget)
        self.lblActualCycle.setGeometry(QtCore.QRect(470, 210, 220, 18))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lblActualCycle.setFont(font)
        self.lblActualCycle.setObjectName(_fromUtf8("lblActualCycle"))
        self.lblActualState = QtGui.QLabel(self.centralwidget)
        self.lblActualState.setGeometry(QtCore.QRect(470, 240, 220, 18))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lblActualState.setFont(font)
        self.lblActualState.setObjectName(_fromUtf8("lblActualState"))
        self.pBtnStation1 = QtGui.QPushButton(self.centralwidget)
        self.pBtnStation1.setGeometry(QtCore.QRect(295, 70, 1, 1))
        font = QtGui.QFont()
        font.setPointSize(2)
        font.setBold(True)
        font.setWeight(75)
        self.pBtnStation1.setFont(font)
        self.pBtnStation1.setText(_fromUtf8(""))
        self.pBtnStation1.setFlat(True)
        self.pBtnStation1.setObjectName(_fromUtf8("pBtnStation1"))
        self.pBtnStation2 = QtGui.QPushButton(self.centralwidget)
        self.pBtnStation2.setGeometry(QtCore.QRect(295, 200, 1, 1))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pBtnStation2.setFont(font)
        self.pBtnStation2.setText(_fromUtf8(""))
        self.pBtnStation2.setFlat(True)
        self.pBtnStation2.setObjectName(_fromUtf8("pBtnStation2"))
        self.pBtnStation3 = QtGui.QPushButton(self.centralwidget)
        self.pBtnStation3.setGeometry(QtCore.QRect(295, 330, 1, 1))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pBtnStation3.setFont(font)
        self.pBtnStation3.setText(_fromUtf8(""))
        self.pBtnStation3.setFlat(True)
        self.pBtnStation3.setObjectName(_fromUtf8("pBtnStation3"))
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Lab Control", None))
        self.btStart.setText(_translate("MainWindow", "START - F5", None))
        self.btStart.setShortcut(_translate("MainWindow", "F5", None))
        self.btnStop.setText(_translate("MainWindow", "STOP - F6", None))
        self.btnStop.setShortcut(_translate("MainWindow", "F6", None))
        self.btnEnd.setText(_translate("MainWindow", "KONIEC - F12", None))
        self.btnEnd.setShortcut(_translate("MainWindow", "F12", None))
        self.gbStation1.setTitle(_translate("MainWindow", "Stanowisko 1", None))
        self.lblSt1Smpl1.setText(_translate("MainWindow", "PRÓBKA 1", None))
        self.lblSt1Smpl2.setText(_translate("MainWindow", "PRÓBKA 2", None))
        self.lblSt1Smpl3.setText(_translate("MainWindow", "PRÓBKA 3", None))
        self.gbStation2.setTitle(_translate("MainWindow", "Stanowisko 2", None))
        self.lblSt2Smpl1.setText(_translate("MainWindow", "PRÓBKA 1", None))
        self.lblSt2Smpl2.setText(_translate("MainWindow", "PRÓBKA 2", None))
        self.lblSt2Smpl3.setText(_translate("MainWindow", "PRÓBKA 3", None))
        self.gbStation3.setTitle(_translate("MainWindow", "Stanowisko 3", None))
        self.lblSt3Smpl1.setText(_translate("MainWindow", "PRÓBKA 1", None))
        self.lblSt3Smpl2.setText(_translate("MainWindow", "PRÓBKA 2", None))
        self.lblSt3Smpl3.setText(_translate("MainWindow", "PRÓBKA 3", None))
        self.tBtnFileSelect.setText(_translate("MainWindow", "...", None))
        self.tBtnFileSelect.setShortcut(_translate("MainWindow", "F4", None))
        self.lblReportFileName.setText(_translate("MainWindow", "Plik raportu:", None))
        self.gbParams.setTitle(_translate("MainWindow", "Parametry testu", None))
        self.sBoxInAirTime.setSuffix(_translate("MainWindow", " m", None))
        self.sBoxFillTime.setSuffix(_translate("MainWindow", " s", None))
        self.sBoxDischargeTime.setSuffix(_translate("MainWindow", " s", None))
        self.sBoxInFluidTime.setSuffix(_translate("MainWindow", " m", None))
        self.pBtnFill.setText(_translate("MainWindow", "NALEWANIE", None))
        self.pBtnFill.setShortcut(_translate("MainWindow", "Alt+N", None))
        self.pBtnInFluid.setText(_translate("MainWindow", "W CIECZY", None))
        self.pBtnInFluid.setShortcut(_translate("MainWindow", "Alt+C", None))
        self.pBtnDischarge.setText(_translate("MainWindow", "WYLEWANIE", None))
        self.pBtnDischarge.setShortcut(_translate("MainWindow", "Alt+W", None))
        self.pBtnInAir.setText(_translate("MainWindow", "W POWIETRZU", None))
        self.pBtnInAir.setShortcut(_translate("MainWindow", "Alt+P", None))
        self.pBtnCycleCounter.setText(_translate("MainWindow", "LICZBA CYKLI", None))
        self.pBtnCycleCounter.setShortcut(_translate("MainWindow", "Alt+L", None))
        self.lblActualCycle.setText(_translate("MainWindow", "Aktualny cykl:", None))
        self.lblActualState.setText(_translate("MainWindow", "Stan próbki:", None))
        self.pBtnStation1.setShortcut(_translate("MainWindow", "F1", None))
        self.pBtnStation2.setShortcut(_translate("MainWindow", "F2", None))
        self.pBtnStation3.setShortcut(_translate("MainWindow", "F3", None))

