# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'controler.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(961, 500)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(960, 500))
        MainWindow.setMaximumSize(QtCore.QSize(961, 501))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gbStation1 = QtWidgets.QGroupBox(self.centralwidget)
        self.gbStation1.setEnabled(True)
        self.gbStation1.setGeometry(QtCore.QRect(10, 10, 345, 155))
        self.gbStation1.setStyleSheet("QGroupBox {\n"
"    border: 1px solid white;\n"
"    border-radius: 9px;\n"
"    margin-top: 0.5em;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    left: 20px;\n"
"    padding: 0 3px 0 3px;\n"
"}")
        self.gbStation1.setCheckable(False)
        self.gbStation1.setObjectName("gbStation1")
        self.lblSt1Smpl1 = QtWidgets.QLabel(self.gbStation1)
        self.lblSt1Smpl1.setGeometry(QtCore.QRect(10, 20, 100, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lblSt1Smpl1.setFont(font)
        self.lblSt1Smpl1.setObjectName("lblSt1Smpl1")
        self.lblSt1Smpl1State = QtWidgets.QLabel(self.gbStation1)
        self.lblSt1Smpl1State.setGeometry(QtCore.QRect(120, 20, 20, 20))
        self.lblSt1Smpl1State.setStyleSheet("border: 1px;\n"
"border-radius: 10px;\n"
"background-color: rgb(255, 0, 0);")
        self.lblSt1Smpl1State.setText("")
        self.lblSt1Smpl1State.setObjectName("lblSt1Smpl1State")
        self.lblSt1Smpl2 = QtWidgets.QLabel(self.gbStation1)
        self.lblSt1Smpl2.setGeometry(QtCore.QRect(10, 55, 100, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lblSt1Smpl2.setFont(font)
        self.lblSt1Smpl2.setObjectName("lblSt1Smpl2")
        self.lblSt1Smpl2State = QtWidgets.QLabel(self.gbStation1)
        self.lblSt1Smpl2State.setGeometry(QtCore.QRect(120, 55, 20, 20))
        self.lblSt1Smpl2State.setStyleSheet("border: 1px;\n"
"border-radius: 10px;\n"
"background-color: rgb(255, 0, 0);")
        self.lblSt1Smpl2State.setText("")
        self.lblSt1Smpl2State.setObjectName("lblSt1Smpl2State")
        self.lblSt1Smpl3 = QtWidgets.QLabel(self.gbStation1)
        self.lblSt1Smpl3.setGeometry(QtCore.QRect(10, 90, 100, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lblSt1Smpl3.setFont(font)
        self.lblSt1Smpl3.setObjectName("lblSt1Smpl3")
        self.lblSt1Smpl3State = QtWidgets.QLabel(self.gbStation1)
        self.lblSt1Smpl3State.setGeometry(QtCore.QRect(120, 90, 20, 20))
        self.lblSt1Smpl3State.setStyleSheet("border: 1px;\n"
"border-radius: 10px;\n"
"background-color: rgb(255, 0, 0);")
        self.lblSt1Smpl3State.setText("")
        self.lblSt1Smpl3State.setObjectName("lblSt1Smpl3State")
        self.btStop_St1 = QtWidgets.QPushButton(self.gbStation1)
        self.btStop_St1.setEnabled(False)
        self.btStop_St1.setGeometry(QtCore.QRect(10, 120, 60, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btStop_St1.setFont(font)
        self.btStop_St1.setStyleSheet("background-color: rgb(85, 0, 0);")
        self.btStop_St1.setObjectName("btStop_St1")
        self.btStart_St1 = QtWidgets.QPushButton(self.gbStation1)
        self.btStart_St1.setGeometry(QtCore.QRect(80, 120, 60, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btStart_St1.setFont(font)
        self.btStart_St1.setStyleSheet("background-color: rgb(0, 85, 0);")
        self.btStart_St1.setObjectName("btStart_St1")
        self.line = QtWidgets.QFrame(self.gbStation1)
        self.line.setGeometry(QtCore.QRect(150, 20, 3, 125))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.pBarPhasePrgs_St1 = QtWidgets.QProgressBar(self.gbStation1)
        self.pBarPhasePrgs_St1.setGeometry(QtCore.QRect(160, 75, 125, 30))
        self.pBarPhasePrgs_St1.setProperty("value", 50)
        self.pBarPhasePrgs_St1.setAlignment(QtCore.Qt.AlignCenter)
        self.pBarPhasePrgs_St1.setOrientation(QtCore.Qt.Horizontal)
        self.pBarPhasePrgs_St1.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.pBarPhasePrgs_St1.setObjectName("pBarPhasePrgs_St1")
        self.lblActCyc_St1 = QtWidgets.QLabel(self.gbStation1)
        self.lblActCyc_St1.setGeometry(QtCore.QRect(160, 25, 170, 18))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lblActCyc_St1.setFont(font)
        self.lblActCyc_St1.setObjectName("lblActCyc_St1")
        self.lblActPhase_St1 = QtWidgets.QLabel(self.gbStation1)
        self.lblActPhase_St1.setGeometry(QtCore.QRect(160, 50, 170, 18))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lblActPhase_St1.setFont(font)
        self.lblActPhase_St1.setObjectName("lblActPhase_St1")
        self.btFill_St1 = QtWidgets.QPushButton(self.gbStation1)
        self.btFill_St1.setGeometry(QtCore.QRect(155, 120, 75, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btFill_St1.setFont(font)
        self.btFill_St1.setStyleSheet("")
        self.btFill_St1.setObjectName("btFill_St1")
        self.btDischarge_St1 = QtWidgets.QPushButton(self.gbStation1)
        self.btDischarge_St1.setGeometry(QtCore.QRect(250, 120, 75, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btDischarge_St1.setFont(font)
        self.btDischarge_St1.setStyleSheet("")
        self.btDischarge_St1.setObjectName("btDischarge_St1")
        self.lblSt1RunState = QtWidgets.QLabel(self.gbStation1)
        self.lblSt1RunState.setGeometry(QtCore.QRect(295, 75, 30, 30))
        self.lblSt1RunState.setStyleSheet("border: 1px;\n"
"border-radius: 15px;\n"
"background-color: rgb(255, 0, 0);")
        self.lblSt1RunState.setText("")
        self.lblSt1RunState.setObjectName("lblSt1RunState")
        self.logView = QtWidgets.QTextEdit(self.centralwidget)
        self.logView.setGeometry(QtCore.QRect(600, 20, 351, 431))
        self.logView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.logView.setReadOnly(True)
        self.logView.setObjectName("logView")
        self.gbStation2 = QtWidgets.QGroupBox(self.centralwidget)
        self.gbStation2.setGeometry(QtCore.QRect(10, 175, 345, 155))
        self.gbStation2.setStyleSheet("QGroupBox {\n"
"    border: 1px solid white;\n"
"    border-radius: 9px;\n"
"    margin-top: 0.5em;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    left: 20px;\n"
"    padding: 0 3px 0 3px;\n"
"}")
        self.gbStation2.setCheckable(False)
        self.gbStation2.setObjectName("gbStation2")
        self.lblSt2Smpl1 = QtWidgets.QLabel(self.gbStation2)
        self.lblSt2Smpl1.setGeometry(QtCore.QRect(10, 20, 100, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lblSt2Smpl1.setFont(font)
        self.lblSt2Smpl1.setObjectName("lblSt2Smpl1")
        self.lblSt2Smpl1State = QtWidgets.QLabel(self.gbStation2)
        self.lblSt2Smpl1State.setGeometry(QtCore.QRect(120, 20, 20, 20))
        self.lblSt2Smpl1State.setStyleSheet("border: 1px;\n"
"border-radius: 10px;\n"
"background-color: rgb(255, 0, 0);")
        self.lblSt2Smpl1State.setText("")
        self.lblSt2Smpl1State.setObjectName("lblSt2Smpl1State")
        self.lblSt2Smpl2 = QtWidgets.QLabel(self.gbStation2)
        self.lblSt2Smpl2.setGeometry(QtCore.QRect(10, 55, 100, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lblSt2Smpl2.setFont(font)
        self.lblSt2Smpl2.setObjectName("lblSt2Smpl2")
        self.lblSt2Smpl2State = QtWidgets.QLabel(self.gbStation2)
        self.lblSt2Smpl2State.setGeometry(QtCore.QRect(120, 55, 20, 20))
        self.lblSt2Smpl2State.setStyleSheet("border: 1px;\n"
"border-radius: 10px;\n"
"background-color: rgb(255, 0, 0);")
        self.lblSt2Smpl2State.setText("")
        self.lblSt2Smpl2State.setObjectName("lblSt2Smpl2State")
        self.lblSt2Smpl3 = QtWidgets.QLabel(self.gbStation2)
        self.lblSt2Smpl3.setGeometry(QtCore.QRect(10, 90, 100, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lblSt2Smpl3.setFont(font)
        self.lblSt2Smpl3.setObjectName("lblSt2Smpl3")
        self.lblSt2Smpl3State = QtWidgets.QLabel(self.gbStation2)
        self.lblSt2Smpl3State.setGeometry(QtCore.QRect(120, 90, 20, 20))
        self.lblSt2Smpl3State.setStyleSheet("border: 1px;\n"
"border-radius: 10px;\n"
"background-color: rgb(255, 0, 0);")
        self.lblSt2Smpl3State.setText("")
        self.lblSt2Smpl3State.setObjectName("lblSt2Smpl3State")
        self.btStop_St2 = QtWidgets.QPushButton(self.gbStation2)
        self.btStop_St2.setEnabled(False)
        self.btStop_St2.setGeometry(QtCore.QRect(10, 120, 60, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btStop_St2.setFont(font)
        self.btStop_St2.setStyleSheet("background-color: rgb(85, 0, 0);")
        self.btStop_St2.setObjectName("btStop_St2")
        self.btStart_St2 = QtWidgets.QPushButton(self.gbStation2)
        self.btStart_St2.setGeometry(QtCore.QRect(80, 120, 60, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btStart_St2.setFont(font)
        self.btStart_St2.setStyleSheet("background-color: rgb(0, 85, 0);")
        self.btStart_St2.setObjectName("btStart_St2")
        self.line_2 = QtWidgets.QFrame(self.gbStation2)
        self.line_2.setGeometry(QtCore.QRect(150, 20, 3, 125))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.lblActCyc_St2 = QtWidgets.QLabel(self.gbStation2)
        self.lblActCyc_St2.setGeometry(QtCore.QRect(160, 25, 170, 18))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lblActCyc_St2.setFont(font)
        self.lblActCyc_St2.setObjectName("lblActCyc_St2")
        self.lblActPhase_St2 = QtWidgets.QLabel(self.gbStation2)
        self.lblActPhase_St2.setGeometry(QtCore.QRect(160, 50, 170, 18))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lblActPhase_St2.setFont(font)
        self.lblActPhase_St2.setObjectName("lblActPhase_St2")
        self.pBarPhasePrgs_St2 = QtWidgets.QProgressBar(self.gbStation2)
        self.pBarPhasePrgs_St2.setGeometry(QtCore.QRect(160, 75, 125, 30))
        self.pBarPhasePrgs_St2.setProperty("value", 50)
        self.pBarPhasePrgs_St2.setAlignment(QtCore.Qt.AlignCenter)
        self.pBarPhasePrgs_St2.setOrientation(QtCore.Qt.Horizontal)
        self.pBarPhasePrgs_St2.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.pBarPhasePrgs_St2.setObjectName("pBarPhasePrgs_St2")
        self.btFill_St2 = QtWidgets.QPushButton(self.gbStation2)
        self.btFill_St2.setGeometry(QtCore.QRect(155, 120, 75, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btFill_St2.setFont(font)
        self.btFill_St2.setStyleSheet("")
        self.btFill_St2.setObjectName("btFill_St2")
        self.btDischarge_St2 = QtWidgets.QPushButton(self.gbStation2)
        self.btDischarge_St2.setGeometry(QtCore.QRect(250, 120, 75, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btDischarge_St2.setFont(font)
        self.btDischarge_St2.setStyleSheet("")
        self.btDischarge_St2.setObjectName("btDischarge_St2")
        self.lblSt2RunState = QtWidgets.QLabel(self.gbStation2)
        self.lblSt2RunState.setGeometry(QtCore.QRect(295, 75, 30, 30))
        self.lblSt2RunState.setStyleSheet("border: 1px;\n"
"border-radius: 15px;\n"
"background-color: rgb(255, 0, 0);")
        self.lblSt2RunState.setText("")
        self.lblSt2RunState.setObjectName("lblSt2RunState")
        self.gbStation3 = QtWidgets.QGroupBox(self.centralwidget)
        self.gbStation3.setGeometry(QtCore.QRect(10, 340, 345, 155))
        self.gbStation3.setStyleSheet("QGroupBox {\n"
"    border: 1px solid white;\n"
"    border-radius: 9px;\n"
"    margin-top: 0.5em;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    left: 20px;\n"
"    padding: 0 3px 0 3px;\n"
"}")
        self.gbStation3.setAlignment(QtCore.Qt.AlignCenter)
        self.gbStation3.setCheckable(False)
        self.gbStation3.setChecked(False)
        self.gbStation3.setObjectName("gbStation3")
        self.lblSt3Smpl1 = QtWidgets.QLabel(self.gbStation3)
        self.lblSt3Smpl1.setGeometry(QtCore.QRect(10, 20, 100, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lblSt3Smpl1.setFont(font)
        self.lblSt3Smpl1.setObjectName("lblSt3Smpl1")
        self.lblSt3Smpl1State = QtWidgets.QLabel(self.gbStation3)
        self.lblSt3Smpl1State.setGeometry(QtCore.QRect(120, 20, 20, 20))
        self.lblSt3Smpl1State.setStyleSheet("border: 1px;\n"
"border-radius: 10px;\n"
"background-color: rgb(255, 0, 0);")
        self.lblSt3Smpl1State.setText("")
        self.lblSt3Smpl1State.setObjectName("lblSt3Smpl1State")
        self.lblSt3Smpl2 = QtWidgets.QLabel(self.gbStation3)
        self.lblSt3Smpl2.setGeometry(QtCore.QRect(10, 55, 100, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lblSt3Smpl2.setFont(font)
        self.lblSt3Smpl2.setObjectName("lblSt3Smpl2")
        self.lblSt3Smpl2State = QtWidgets.QLabel(self.gbStation3)
        self.lblSt3Smpl2State.setGeometry(QtCore.QRect(120, 55, 20, 20))
        self.lblSt3Smpl2State.setStyleSheet("border: 1px;\n"
"border-radius: 10px;\n"
"background-color: rgb(255, 0, 0);")
        self.lblSt3Smpl2State.setText("")
        self.lblSt3Smpl2State.setObjectName("lblSt3Smpl2State")
        self.lblSt3Smpl3 = QtWidgets.QLabel(self.gbStation3)
        self.lblSt3Smpl3.setGeometry(QtCore.QRect(10, 90, 100, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lblSt3Smpl3.setFont(font)
        self.lblSt3Smpl3.setObjectName("lblSt3Smpl3")
        self.lblSt3Smpl3State = QtWidgets.QLabel(self.gbStation3)
        self.lblSt3Smpl3State.setGeometry(QtCore.QRect(120, 90, 20, 20))
        self.lblSt3Smpl3State.setStyleSheet("border: 1px;\n"
"border-radius: 10px;\n"
"background-color: rgb(255, 0, 0);")
        self.lblSt3Smpl3State.setText("")
        self.lblSt3Smpl3State.setObjectName("lblSt3Smpl3State")
        self.btStop_St3 = QtWidgets.QPushButton(self.gbStation3)
        self.btStop_St3.setEnabled(False)
        self.btStop_St3.setGeometry(QtCore.QRect(10, 120, 60, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btStop_St3.setFont(font)
        self.btStop_St3.setStyleSheet("background-color: rgb(85, 0, 0);")
        self.btStop_St3.setObjectName("btStop_St3")
        self.btStart_St3 = QtWidgets.QPushButton(self.gbStation3)
        self.btStart_St3.setGeometry(QtCore.QRect(80, 120, 60, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btStart_St3.setFont(font)
        self.btStart_St3.setStyleSheet("background-color: rgb(0, 85, 0);")
        self.btStart_St3.setObjectName("btStart_St3")
        self.line_3 = QtWidgets.QFrame(self.gbStation3)
        self.line_3.setGeometry(QtCore.QRect(150, 20, 3, 125))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.lblActCyc_St3 = QtWidgets.QLabel(self.gbStation3)
        self.lblActCyc_St3.setGeometry(QtCore.QRect(160, 25, 170, 18))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lblActCyc_St3.setFont(font)
        self.lblActCyc_St3.setObjectName("lblActCyc_St3")
        self.lblActPhase_St3 = QtWidgets.QLabel(self.gbStation3)
        self.lblActPhase_St3.setGeometry(QtCore.QRect(160, 50, 170, 18))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lblActPhase_St3.setFont(font)
        self.lblActPhase_St3.setObjectName("lblActPhase_St3")
        self.pBarPhasePrgs_St3 = QtWidgets.QProgressBar(self.gbStation3)
        self.pBarPhasePrgs_St3.setGeometry(QtCore.QRect(160, 75, 125, 30))
        self.pBarPhasePrgs_St3.setProperty("value", 50)
        self.pBarPhasePrgs_St3.setAlignment(QtCore.Qt.AlignCenter)
        self.pBarPhasePrgs_St3.setOrientation(QtCore.Qt.Horizontal)
        self.pBarPhasePrgs_St3.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.pBarPhasePrgs_St3.setObjectName("pBarPhasePrgs_St3")
        self.btFill_St3 = QtWidgets.QPushButton(self.gbStation3)
        self.btFill_St3.setGeometry(QtCore.QRect(155, 120, 75, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btFill_St3.setFont(font)
        self.btFill_St3.setStyleSheet("")
        self.btFill_St3.setObjectName("btFill_St3")
        self.btDischarge_St3 = QtWidgets.QPushButton(self.gbStation3)
        self.btDischarge_St3.setGeometry(QtCore.QRect(250, 120, 75, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btDischarge_St3.setFont(font)
        self.btDischarge_St3.setStyleSheet("")
        self.btDischarge_St3.setObjectName("btDischarge_St3")
        self.lblSt3RunState = QtWidgets.QLabel(self.gbStation3)
        self.lblSt3RunState.setGeometry(QtCore.QRect(295, 75, 30, 30))
        self.lblSt3RunState.setStyleSheet("border: 1px;\n"
"border-radius: 15px;\n"
"background-color: rgb(255, 0, 0);")
        self.lblSt3RunState.setText("")
        self.lblSt3RunState.setObjectName("lblSt3RunState")
        self.gbParams = QtWidgets.QGroupBox(self.centralwidget)
        self.gbParams.setGeometry(QtCore.QRect(360, 10, 231, 251))
        self.gbParams.setStyleSheet("QGroupBox {\n"
"    border: 1px solid white;\n"
"    border-radius: 9px;\n"
"    margin-top: 0.5em;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    left: 10px;\n"
"    padding: 0 3px 0 3px;\n"
"}")
        self.gbParams.setCheckable(False)
        self.gbParams.setObjectName("gbParams")
        self.sBoxCycleCounter = QtWidgets.QSpinBox(self.gbParams)
        self.sBoxCycleCounter.setGeometry(QtCore.QRect(135, 145, 80, 22))
        self.sBoxCycleCounter.setAlignment(QtCore.Qt.AlignCenter)
        self.sBoxCycleCounter.setMinimum(1)
        self.sBoxCycleCounter.setMaximum(9999)
        self.sBoxCycleCounter.setProperty("value", 10)
        self.sBoxCycleCounter.setObjectName("sBoxCycleCounter")
        self.sBoxInAirTime = QtWidgets.QSpinBox(self.gbParams)
        self.sBoxInAirTime.setGeometry(QtCore.QRect(135, 115, 80, 22))
        self.sBoxInAirTime.setAlignment(QtCore.Qt.AlignCenter)
        self.sBoxInAirTime.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.sBoxInAirTime.setSpecialValueText("")
        self.sBoxInAirTime.setMinimum(1)
        self.sBoxInAirTime.setMaximum(9999)
        self.sBoxInAirTime.setProperty("value", 10)
        self.sBoxInAirTime.setObjectName("sBoxInAirTime")
        self.sBoxFillTime = QtWidgets.QSpinBox(self.gbParams)
        self.sBoxFillTime.setGeometry(QtCore.QRect(135, 22, 80, 22))
        self.sBoxFillTime.setAlignment(QtCore.Qt.AlignCenter)
        self.sBoxFillTime.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.sBoxFillTime.setMinimum(1)
        self.sBoxFillTime.setMaximum(9999)
        self.sBoxFillTime.setProperty("value", 60)
        self.sBoxFillTime.setObjectName("sBoxFillTime")
        self.sBoxDischargeTime = QtWidgets.QSpinBox(self.gbParams)
        self.sBoxDischargeTime.setGeometry(QtCore.QRect(135, 85, 80, 22))
        self.sBoxDischargeTime.setAlignment(QtCore.Qt.AlignCenter)
        self.sBoxDischargeTime.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.sBoxDischargeTime.setSpecialValueText("")
        self.sBoxDischargeTime.setMinimum(1)
        self.sBoxDischargeTime.setMaximum(9999)
        self.sBoxDischargeTime.setProperty("value", 60)
        self.sBoxDischargeTime.setObjectName("sBoxDischargeTime")
        self.sBoxInFluidTime = QtWidgets.QSpinBox(self.gbParams)
        self.sBoxInFluidTime.setGeometry(QtCore.QRect(135, 55, 80, 22))
        self.sBoxInFluidTime.setAlignment(QtCore.Qt.AlignCenter)
        self.sBoxInFluidTime.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.sBoxInFluidTime.setSpecialValueText("")
        self.sBoxInFluidTime.setMinimum(1)
        self.sBoxInFluidTime.setMaximum(9999)
        self.sBoxInFluidTime.setProperty("value", 10)
        self.sBoxInFluidTime.setObjectName("sBoxInFluidTime")
        self.pBtnFill = QtWidgets.QPushButton(self.gbParams)
        self.pBtnFill.setGeometry(QtCore.QRect(10, 22, 120, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pBtnFill.setFont(font)
        self.pBtnFill.setStyleSheet("Text-align: right")
        self.pBtnFill.setFlat(True)
        self.pBtnFill.setObjectName("pBtnFill")
        self.pBtnInFluid = QtWidgets.QPushButton(self.gbParams)
        self.pBtnInFluid.setGeometry(QtCore.QRect(10, 55, 120, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pBtnInFluid.setFont(font)
        self.pBtnInFluid.setStyleSheet("Text-align: right")
        self.pBtnInFluid.setFlat(True)
        self.pBtnInFluid.setObjectName("pBtnInFluid")
        self.pBtnDischarge = QtWidgets.QPushButton(self.gbParams)
        self.pBtnDischarge.setGeometry(QtCore.QRect(10, 85, 120, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pBtnDischarge.setFont(font)
        self.pBtnDischarge.setStyleSheet("Text-align: right")
        self.pBtnDischarge.setFlat(True)
        self.pBtnDischarge.setObjectName("pBtnDischarge")
        self.pBtnInAir = QtWidgets.QPushButton(self.gbParams)
        self.pBtnInAir.setGeometry(QtCore.QRect(10, 115, 120, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pBtnInAir.setFont(font)
        self.pBtnInAir.setStyleSheet("Text-align: right")
        self.pBtnInAir.setFlat(True)
        self.pBtnInAir.setObjectName("pBtnInAir")
        self.pBtnCycleCounter = QtWidgets.QPushButton(self.gbParams)
        self.pBtnCycleCounter.setGeometry(QtCore.QRect(10, 145, 120, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pBtnCycleCounter.setFont(font)
        self.pBtnCycleCounter.setStyleSheet("Text-align: right")
        self.pBtnCycleCounter.setFlat(True)
        self.pBtnCycleCounter.setObjectName("pBtnCycleCounter")
        self.lEditFileName = QtWidgets.QLineEdit(self.gbParams)
        self.lEditFileName.setGeometry(QtCore.QRect(5, 210, 221, 29))
        self.lEditFileName.setObjectName("lEditFileName")
        self.btPathSelect = QtWidgets.QPushButton(self.gbParams)
        self.btPathSelect.setGeometry(QtCore.QRect(195, 180, 29, 29))
        self.btPathSelect.setObjectName("btPathSelect")
        self.lblReportFileName = QtWidgets.QLabel(self.gbParams)
        self.lblReportFileName.setGeometry(QtCore.QRect(5, 185, 141, 20))
        self.lblReportFileName.setObjectName("lblReportFileName")
        self.pBtnClearLog = QtWidgets.QPushButton(self.centralwidget)
        self.pBtnClearLog.setGeometry(QtCore.QRect(820, 460, 131, 29))
        self.pBtnClearLog.setObjectName("pBtnClearLog")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Lab Control"))
        self.gbStation1.setTitle(_translate("MainWindow", "Stanowisko 1"))
        self.lblSt1Smpl1.setText(_translate("MainWindow", "PRÓBKA 1"))
        self.lblSt1Smpl2.setText(_translate("MainWindow", "PRÓBKA 2"))
        self.lblSt1Smpl3.setText(_translate("MainWindow", "PRÓBKA 3"))
        self.btStop_St1.setText(_translate("MainWindow", "STOP"))
        self.btStart_St1.setText(_translate("MainWindow", "START"))
        self.lblActCyc_St1.setText(_translate("MainWindow", "Cykl:"))
        self.lblActPhase_St1.setText(_translate("MainWindow", "Faza: W POWIETRZU"))
        self.btFill_St1.setText(_translate("MainWindow", "NALEWAJ"))
        self.btDischarge_St1.setText(_translate("MainWindow", "WYLEWAJ"))
        self.logView.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p></body></html>"))
        self.gbStation2.setTitle(_translate("MainWindow", "Stanowisko 2"))
        self.lblSt2Smpl1.setText(_translate("MainWindow", "PRÓBKA 1"))
        self.lblSt2Smpl2.setText(_translate("MainWindow", "PRÓBKA 2"))
        self.lblSt2Smpl3.setText(_translate("MainWindow", "PRÓBKA 3"))
        self.btStop_St2.setText(_translate("MainWindow", "STOP"))
        self.btStart_St2.setText(_translate("MainWindow", "START"))
        self.lblActCyc_St2.setText(_translate("MainWindow", "Cykl:"))
        self.lblActPhase_St2.setText(_translate("MainWindow", "Faza:"))
        self.btFill_St2.setText(_translate("MainWindow", "NALEWAJ"))
        self.btDischarge_St2.setText(_translate("MainWindow", "WYLEWAJ"))
        self.gbStation3.setTitle(_translate("MainWindow", "Stanowisko 3"))
        self.lblSt3Smpl1.setText(_translate("MainWindow", "PRÓBKA 1"))
        self.lblSt3Smpl2.setText(_translate("MainWindow", "PRÓBKA 2"))
        self.lblSt3Smpl3.setText(_translate("MainWindow", "PRÓBKA 3"))
        self.btStop_St3.setText(_translate("MainWindow", "STOP"))
        self.btStart_St3.setText(_translate("MainWindow", "START"))
        self.lblActCyc_St3.setText(_translate("MainWindow", "Cykl:"))
        self.lblActPhase_St3.setText(_translate("MainWindow", "Faza:"))
        self.btFill_St3.setText(_translate("MainWindow", "NALEWAJ"))
        self.btDischarge_St3.setText(_translate("MainWindow", "WYLEWAJ"))
        self.gbParams.setTitle(_translate("MainWindow", "Parametry testu"))
        self.sBoxInAirTime.setSuffix(_translate("MainWindow", " m"))
        self.sBoxFillTime.setSuffix(_translate("MainWindow", " s"))
        self.sBoxDischargeTime.setSuffix(_translate("MainWindow", " s"))
        self.sBoxInFluidTime.setSuffix(_translate("MainWindow", " m"))
        self.pBtnFill.setText(_translate("MainWindow", "NALEWANIE"))
        self.pBtnFill.setShortcut(_translate("MainWindow", "Alt+N"))
        self.pBtnInFluid.setText(_translate("MainWindow", "W CIECZY"))
        self.pBtnInFluid.setShortcut(_translate("MainWindow", "Alt+C"))
        self.pBtnDischarge.setText(_translate("MainWindow", "WYLEWANIE"))
        self.pBtnDischarge.setShortcut(_translate("MainWindow", "Alt+W"))
        self.pBtnInAir.setText(_translate("MainWindow", "W POWIETRZU"))
        self.pBtnInAir.setShortcut(_translate("MainWindow", "Alt+P"))
        self.pBtnCycleCounter.setText(_translate("MainWindow", "LICZBA CYKLI"))
        self.pBtnCycleCounter.setShortcut(_translate("MainWindow", "Alt+L"))
        self.btPathSelect.setText(_translate("MainWindow", "..."))
        self.btPathSelect.setShortcut(_translate("MainWindow", "F4"))
        self.lblReportFileName.setText(_translate("MainWindow", "Lokalizacja raportu:"))
        self.pBtnClearLog.setText(_translate("MainWindow", "WYCZYŚC LOG"))
        self.pBtnClearLog.setShortcut(_translate("MainWindow", "F4"))

